### ISSUE TITLE
loginWith promise result is undefined

### ISSUE THREAD

**Issue by Guito** [nuxt/consola#11]
### Version

[v4.1.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.1.0)

### Reproduction link

[https://nuxt-auth.herokuapp.com/](https://nuxt-auth.herokuapp.com/)

### Steps to reproduce

The following code logs undefined:

    
            return this.$auth.loginWith('local', {
                    data: {
                        username: this.username,
                        password: this.password
                    }
                }).then(response => {
                    console.log(response);
                }

### What is expected ?

Getting the full response

### What is actually happening?

Response is undefined

EDIT: This is for the AUTH project, not consola. Is it possible to move this? I have not found out how.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c6">#c6</a>)</em></sub></div>

**Comment by pi0** [comment]
https://github.com/nuxt-community/auth-module/issues/144
