### ISSUE TITLE
nuxt-typescript example has `vue is not defined` error

### ISSUE THREAD

**Issue by alidcastano** [nuxt/consola#12]
### Version

[1.4.0](https://github.com/nuxt/consola/releases/tag/1.4.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript](https://github.com/nuxt/nuxt.js/tree/dev/examples/typescript)

### Steps to reproduce

run fresh example

### What is expected ?

no errors 

### What is actually happening?

`Vue is not defined` error likely due to a ssr issue, which might cause problems in production 

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c7">#c7</a>)</em></sub></div>

**Comment by pi0** [comment]
Not related to this repo: https://github.com/nuxt/nuxt.js/issues/3226
