### ISSUE TITLE
Error when using nuxt in electron SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/consola#13]
### Version

[1.4+](https://github.com/nuxt/consola/releases/tag/1.4+)

### Reproduction link

[https://electronjs.org/docs](https://electronjs.org/docs)
[nuxt-issues](https://github.com/nuxt/nuxt.js/issues/3215)

### Steps to reproduce

Error when using nuxt in electron SyntaxError: Unexpected token ...

### What is expected ?

Looking to replace nuxt with 72 lines {...this.options.render.csp.policies} instead of using...
![99-1.png](https://cmty.s3.eu-west-1.amazonaws.com/127546642/7a975cb0-3d78-11e8-b907-4158a744457b.png)

### What is actually happening?

Error when using nuxt in electron SyntaxError: Unexpected token ...

![99-2.png](https://cmty.s3.eu-west-1.amazonaws.com/127546642/a61a6e40-3d78-11e8-b907-4158a744457b.png)

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c8">#c8</a>)</em></sub></div>

**Comment by pi0** [comment]
https://github.com/nuxt/nuxt.js/issues/3215
