### ISSUE TITLE
Object is undefined if not stringified (JSON.stringify)

### ISSUE THREAD

**Issue by Jeromearsene** [nuxt/consola#16]
I have an object to log.

I do this:
```
    console.log(professionnalInfos);
    logger.info(professionnalInfos);
    logger.info(JSON.stringify(professionnalInfos));
```

Result:
```
{ siren: '1111111', phone: '0511111111' }
ℹ info undefined
ℹ info {"siren":"1111111","phone":"0511111111"}
```

I think `undefined` is counter intuitive. No ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c26">#c26</a>)</em></sub></div>

**Comment by Bjornskjald** [comment]
Why was this closed? I just ran into the same unexpected issue.

**Comment by pi0** [comment]
With [v2.0.0](https://github.com/nuxt/consola/releases/tag/v2.0.0) We have a cleaner way to log things. But still suggested using the second argument for displaying objects to prevent conflicting with logObj can more fancier lines :)
