### ISSUE TITLE
The page returned to the home page on wechat

### ISSUE THREAD

**Issue by hqqxxf** [nuxt/consola#17]
### Version

[1.4.0](https://github.com/nuxt/consola/releases/tag/1.4.0)

### Reproduction link

[https://jsfiddle.net/hqqxxf/edLsh8sL/](https://jsfiddle.net/hqqxxf/edLsh8sL/)

### Steps to reproduce

in router '/a', it has a link to '/b', when I returned in '/b', The page returned to the home page('/') , and I found not the static resources request when returned.

### What is expected ?

returned to the last page(router '/a')

### What is actually happening?

returned to the home page(router '/' or 404)

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c30">#c30</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@hqqxxf I think you opened issue at wrong repo.
