### ISSUE TITLE
ci-info module throw error for "process is not defined"

### ISSUE THREAD

**Issue by tim-yao** [nuxt/consola#19]
### Version

[1.3.0](https://github.com/nuxt/consola/releases/tag/1.3.0)

### Reproduction link

[https://codepen.io/timyaodpc/pen/bMyazm](https://codepen.io/timyaodpc/pen/bMyazm)

### Steps to reproduce

Use it in Nuxt/plugins/myplugin.js.

It all works but in browser console it give me a error says `"process is not defined"`. Error points to `"ci-info"` module first line which tries to use `process.env`.

I can see ci-info is a dependency of consola as below:

└─┬ consola@1.3.0
  └─┬ std-env@1.3.0
    └─┬ is-ci@1.1.0
      └── ci-info@1.1.3

I now have to add `isServer` condition on `const consola = require('consola')`. Otherwise it breaks the client side.

### What is expected ?

Browser should no error in console.

### What is actually happening?

A error from `ci-info` says "process is not defined".

> index.js:3 Uncaught ReferenceError: process is not defined
    at Object../node_modules/ci-info/index.js (index.js:3)
    at __webpack_require__ (bootstrap 20212f6dd5b287d60bc9:712)
    at fn (bootstrap 20212f6dd5b287d60bc9:117)
    at Object../node_modules/is-ci/index.js (index.js:3)
    at __webpack_require__ (bootstrap 20212f6dd5b287d60bc9:712)
    at fn (bootstrap 20212f6dd5b287d60bc9:117)
    at Object.<anonymous> (index.js:1)
    at Object../node_modules/std-env/index.js (index.js:18)
    at __webpack_require__ (bootstrap 20212f6dd5b287d60bc9:712)
    at fn (bootstrap 20212f6dd5b287d60bc9:117)

### Additional comments?
Is `Consola` can only be used in server side js?
The consola code index.js first line imported `std-env` which can only used in server side.
https://github.com/nuxt/consola/blob/master/src/index.js#L1
Not sure which is the best way to use it in Nuxt and maybe it's a bug?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/consola/issues/c32">#c32</a>)</em></sub></div>

**Comment by Mucaccino** [comment]
How about that? The same on 1.4.1 version.

**Comment by benfavre** [comment]
Same on nuxt-edge.

Would like to see someone release a wrapper plugin/module for nuxt with server side only loging function and client side only or both, and a flag to ajust logging level based on node_env.

Great work so far. Thanks !

**Comment by clarkdo** [comment]
@tim-yao 
The current Consola is indeed a logger for Node.js, so it's not supported in client side.

@benfavre 
Maybe it's not very appropriate to add a plugin or module, because that codes cannot be optimized in client building.

I suggest to use `process.server` in Nuxt to wrap the logging codes, for example:

```js
if(process.server) {
  Consola.log('this block will be removed in client side by webpack')
}
```

**Comment by tim-yao** [comment]
Thanks @clarkdo As it is not suppose to be used in Node.js only, I will close this issue now. But maybe worth to add some description in Readme.

**Comment by SalvadorDuran** [comment]
I'm having the same issue right now since I yarn upgrade to the last version of nuxt. I'm not using consola... Any solution?

**Comment by marcDeSantis** [comment]
Are there plans for addressing this? I don't see how consola is meant to be used with this bug in place.

**Comment by pi0** [comment]
Official browser support has arrived with [v2.0.0](https://github.com/nuxt/consola/releases/tag/v2.0.0). It only takes 1.5KB / Gzipped for the browser.

**Comment by manniL** [comment]
![image](https://user-images.githubusercontent.com/640208/47937851-0f8dfb00-deda-11e8-84ba-eeed7f04b2e3.png)
:heart:
