### ISSUE TITLE
ci-info module throw error for "process is not defined" again

### ISSUE THREAD

**Issue by kazumi-kondo-forgevision** [nuxt/consola#21]
please reopen this issue.
https://github.com/nuxt/consola/issues/19

---
    "@nuxtjs/axios": {
      "version": "5.3.1",
---
    "consola": {
      "version": "1.4.1",
---
    "std-env": {
      "version": "1.3.1",
---
    "is-ci": {
      "version": "1.1.0",
---
    "ci-info": {
      "version": "1.1.3",
---

**Comment by waghcwb** [comment]
@kazumi-kondo-forgevision,

I was having the same issue, the problema was that `consola` was with an outdated version. So, I installed the `consola` manually and the error goes away
`npm i consola -D`
