### ISSUE TITLE
docs: improve mocking guide

### ISSUE THREAD

**Issue by manniL** [nuxt/consola#25]
### What problem does this feature solve?

~~It'd be great to have a few examples on how to mock `consola` (default, but also `withScope`) :relaxed:~~

We already have examples in the README, but a few more words to each wouldn't be bad :relaxed: 

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c36">#c36</a>)</em></sub></div>

**Comment by pi0** [comment]
Related release for better mocking support: https://github.com/nuxt/consola/releases/tag/v2.1.0
