### ISSUE TITLE
[feature request] Log level variable

### ISSUE THREAD

**Issue by Bjornskjald** [nuxt/consola#3]
I mean something like in `npmlog` to hide logs below certain level

**Comment by pi0** [comment]
Hi. What about doing this:

```js
const consola = require('consola')

consola.level = 5
```
Levels are defined [here](https://github.com/nuxt/consola/blob/master/src/types.js)

If this trick works, making a PR to document it would be nice!

**Comment by Psychokrameur** [comment]
Hello, do you know how to define `CONSOLA_LEVEL` globally?
I tried in nuxt.config.js with 
```
env: {
    CONSOLA_LEVEL:4
} 
```
but doesn't work...

**Comment by pi0** [comment]
@Psychokrameur You have to update it using the above method or providing environment variables. options.env is for runtime bundle not node.js

**Comment by Psychokrameur** [comment]
Ok thanks @pi0.

**Comment by gkatsanos** [comment]
@pi0  can I pass a different CONSOLA_LEVEL from the npm script / cli directly?
