### ISSUE TITLE
Maximum call stack size exceeded in browser?

### ISSUE THREAD

**Issue by Tom-Bonnike** [nuxt/consola#31]
### Version

[2.2.3](https://github.com/consola/releases/tag/2.2.3)

### Reproduction link

[https://codesandbox.io/s/vj522nv827](https://codesandbox.io/s/vj522nv827)

### Steps to reproduce

- Use `wrapAll` 
- Use any console.* method after that

### What is expected ?

The log is enhanced

### What is actually happening?

- The page crashes because of maximum call stack size exceeded.
- The browser reporter keeps on calling itself.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c40">#c40</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks, @Tom-Bonnike for the reported. Fixed in 2.3.0.

**Comment by ESoch** [comment]
@pi0, how was this fixed? I am running into this problem again with `2.15.3`.
