### ISSUE TITLE
Export dist for src/index.js

### ISSUE THREAD

**Issue by pimlie** [nuxt/consola#45]
### What problem does this feature solve?

Previous versions of consola exported all the internals which I used to create my own Consola instance in nuxt-generate-cluster: https://github.com/nuxt-community/nuxt-generate-cluster/blob/master/lib/utils/consola.js

Currently it seems the only export that is distributed is the consola instance. Which also means that the README is probably not correct. Eg when I log `consola.JSONReporter` it logs `undefined` (referring to this: https://github.com/nuxt/consola#creating-a-new-instance)

### What does the proposed changes look like?

I'd also be happy with a third build file, eg so I have to import eg `consola/dist/Consola` to get access to all the exports in https://github.com/nuxt/consola/blob/master/src/index.js

Not sure what the best name for such an export would be

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c46">#c46</a>)</em></sub></div>

**Comment by pimlie** [comment]
@pi0 This morning I remembered that you made consola to be a small as possible, maybe we could add a `consola-es` of `consola-full` package then which just distributes the source? That way we can still have the small 1.6k gzipped package but also hook into consola's inner workings.

**Comment by pi0** [comment]
@pimlie Sorry for missing this Issue. What do you think if we distribute extra reporters (other than basic, fancy) as external packages and converting this into a mono repo? BTW other than reporters, what other internal needs to be expose / customized for your use case?

**Comment by pimlie** [comment]
Besides the `BasicReporter` and `FancyReporter` I use:

- the `Consola` class from `src/consola.js` to create my own instance
- the default `Types` from `src/types.js` to add some custom types
But I only need these because afaik you can only set types on a new consola instance. Eg if you could also add types which are then merged (and the added types with the same name have preference) with the default types (instead of that they overwrite them) I wouldnt need this export

A mono repository sounds like a lot of work? I am happy with any solution, so please do as what you think is best. That said, if you would go for a mono repo maybe we could also add something similar as the cluster reporter I use to it? Would that be something which could also be used for nuxt workers?

Eg the main idea behind the ClusterReporter is that all child processes report their logs to the consola instance on the master process. That way you eg wont have any issues if you want to add a FileReporter to log all the logs from all workers to a single file.

**Comment by bboure** [comment]
Hi,

I am facing similar issues. Since Reporters are not exposed, how would you pass custom options to a Reporter? 
https://github.com/nuxt/consola/blob/master/src/reporters/fancy.js#L27

**Comment by pi0** [comment]
Built-in reporters are created in singleton instance of consola and are somehow optionized. You can set default reporter options via `consola._reporters[0].options`

**Comment by pimlie** [comment]
Will close this as I managed to fix it with the updated api. I guess the main issue was that I had the wrong mindset, looking at it now I think 2.4 should have been 3.0 as removing the exports was a breaking change :)

Also: https://xkcd.com/1172/

**Comment by pi0** [comment]
Consola and reporters exposed again in 2.6.0 (3a8f6627d30c161a1b40542d5416e09c2b52751f)
