### ISSUE TITLE
Incorrect cmty link in issue template

### ISSUE THREAD

**Issue by duyleekun** [nuxt/consola#53]
### Version

[2.8.1](https://github.com/consola/releases/tag/2.8.1)

### Reproduction link

[https://github.com/nuxt/consola/issues/new](https://github.com/nuxt/consola/issues/new)

### Steps to reproduce

- Create new issue in Github
- https://nuxtjs.cmty.io/issues/new is invalid url

### What is expected ?

https://cmty.app/nuxt/issues/new?type=bug-report&repo=consola

### What is actually happening?

https://nuxtjs.cmty.io/issues/new

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c51">#c51</a>)</em></sub></div>

**Comment by Atinux** [comment]
Fixed thank you :)
