### ISSUE TITLE
Spam not logged without trailing call

### ISSUE THREAD

**Issue by pimlie** [nuxt/consola#68]
The `repeated X times` is only triggered with a trailing consola call. If you dont have a trailing consola call the spam message doesnt get printed.

See https://jsfiddle.net/6pvqxy1k/1/ for an example, without the END call the `(repeated 4 times)` message will never be printed

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c59">#c59</a>)</em></sub></div>

**Comment by nevf** [comment]
This seems to be a fundamental issue in a recent release. Whenever a repeated consola call is made with the same content and no other consola call follows this, you don't see any output. 

IMO this is a serious bug as this consola output is never displayed.
