### ISSUE TITLE
An export assignment cannot be used in a module with other exported elements

### ISSUE THREAD

**Issue by Ckeyang** [nuxt/consola#86]
**how to solve this problem**
ERROR in D:/web/test-nuxt-ts/node_modules/consola/types/consola.d.ts
ERROR in D:/web/test-nuxt-ts/node_modules/consola/types/consola.d.ts(98,1):
98:1 An export assignment cannot be used in a module with other exported elements.
    96 | export default consolaGlobalInstance
    97 | 
  > 98 | export = consolaGlobalInstance
       | ^
    99 | 

 FATAL  Nuxt build error

**Comment by remipe-utbm** [comment]
@pi0 Hello, I'm metting the exact same problem since I upgraded Nuxt to version 2.11.0.
