### ISSUE TITLE
Export assignment error in consola.d.ts

### ISSUE THREAD

**Issue by asasas333** [nuxt/consola#88]
### Version

[v2.11.2](https://github.com/consola/releases/tag/v2.11.2)

### Reproduction link

[https://jsfiddle.net/6hj9wd35/](https://jsfiddle.net/6hj9wd35/)

### Steps to reproduce

Run a project with latest version

### What is expected ?

Remove incorrect export, line 98
https://github.com/nuxt/consola/commit/5c22d8cd4624e3bbd7294b9eba09f131ed786332

### What is actually happening?

 An export assignment cannot be used in a module with other exported elements.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c67">#c67</a>)</em></sub></div>

**Comment by pi0** [comment]
Fixed. Thanks for your patience.
